"""Strict readiness evaluation. Missing external acceptance evidence blocks release."""
import math
import hashlib
import re
from pathlib import Path

# Every technical check the evidence run must record as True.
REQUIRED_CHECKS = [
    'component_tests', 'fresh_rejection_no_partial', 'fresh_registration', 'idempotent_retry',
    'rejection_unchanged', 'restart_identity_preserved', 'postgres_health_failure', 'redis_health_failure',
    'dependency_recovery', 'redaction', 'correlation', 'latency', 'cleanup', 'security_integration',
    'consumer_recovery', 'poison_out_of_order', 'durable_idempotency', 'outbox_recovery',
    'service_owned_permissions', 'monitoring', 'synthetic_console',
]
MIN_LATENCY_SAMPLES = 20
MAX_P95_MS = 3000


def evaluate(report, prerequisite=None, review=None, evidence_directory=None):
    errors = []
    for name in REQUIRED_CHECKS:
        if report.get('checks', {}).get(name) is not True:
            errors.append('missing/failed: ' + name)
    values = report.get('latency_ms', [])
    if len(values) < MIN_LATENCY_SAMPLES or any(type(v) not in (float, int) or not math.isfinite(v) or v < 0 for v in values):
        errors.append('invalid/missing latency measurements')
    elif sorted(values)[math.ceil(.95 * len(values)) - 1] > MAX_P95_MS:
        errors.append('registration p95 exceeds 3000 ms')
    if report.get('measurement', {}).get('requested_samples') != len(values):
        errors.append('incomplete measurement series')
    if report.get('source_unchanged') is not True:
        errors.append('source changed or not recorded')
    artifacts = report.get('artifacts', {})
    if not artifacts or evidence_directory is None:
        errors.append('artifact manifest or directory missing')
    else:
        root = Path(evidence_directory).resolve()
        for name, expected in artifacts.items():
            path = (root / name).resolve()
            if not path.is_relative_to(root) or not path.is_file():
                errors.append('missing artifact: ' + name)
            elif hashlib.sha256(path.read_bytes()).hexdigest() != expected:
                errors.append('changed artifact: ' + name)
    if report.get('failure'):
        errors.append('execution failed')
    blockers = []
    waivers = []
    fingerprint = report.get('source_sha256')
    if not isinstance(fingerprint, str) or not re.fullmatch('[0-9a-f]{64}', fingerprint):
        errors.append('missing/invalid source fingerprint')
    # These records must be produced by actual team review, never autogenerated as PASS.
    for label, record, fields in [
        ('Issue 7', prerequisite, ['postgres_redis_integration', 'durable_idempotency',
          'consumer_recovery', 'poison_out_of_order', 'service_owned_permissions']),
        ('review/reproduction', review, ['clean_checkout_reproduced', 'independent_reproduction',
          'backup_handoff', 'independent_trust_review', 'accepted']),
    ]:
        if not isinstance(record, dict) or record.get('source_sha256') != fingerprint:
            blockers.append(label + ': absent or different source version')
            continue
        if not record.get('reviewer') or not record.get('evidence_reference'):
            blockers.append(label + ': reviewer or evidence reference missing')
        for field in fields:
            if record.get(field) is True:
                continue
            waiver = waiver_for(record, field)
            if waiver:
                waivers.append(label + ': ' + field + ' waived by ' + waiver)
            else:
                blockers.append(label + ': ' + field)
    return {'status': 'FAIL' if errors else 'BLOCKED' if blockers else 'PASS',
            'technical_checks': 'FAIL' if errors else 'PASS', 'errors': errors, 'blockers': blockers,
            'waivers': waivers}


def waiver_for(record, field):
    """A named person may waive an acceptance check that was not done. `accepted` cannot be waived."""
    reason = record.get('waivers', {}).get(field) if isinstance(record.get('waivers'), dict) else None
    approver = record.get('waived_by')
    if field == 'accepted' or not isinstance(reason, str) or not reason.strip() or not approver:
        return None
    return approver + ': ' + reason.strip()

if __name__ == '__main__':
    import argparse
    import json
    import sys
    parser = argparse.ArgumentParser()
    parser.add_argument('run', type=Path)
    parser.add_argument('--prerequisites', type=Path)
    parser.add_argument('--review', type=Path)
    args = parser.parse_args()
    try:
        read = lambda path: json.loads(path.read_text()) if path else None
        result = evaluate(read(args.run), read(args.prerequisites), read(args.review), args.run.parent)
    except Exception:
        result = {'status': 'FAIL', 'errors': ['Invalid or missing evidence record']}
    print(json.dumps(result, indent=2))
    sys.exit(0 if result['status'] == 'PASS' else 2 if result['status'] == 'BLOCKED' else 1)
